### ISSUE TITLE
Corregir data enviada por https://igna98.alwaysdata.net/page

### ISSUE THREAD

**Issue by WalterCerto** [gnuno/bot-info-uno#12]
No se puede acceder a la pagina de las **_Comunidades IT_** por medio de la url otorgada por el bot. 
Ya que 'data' indica un "name" erroneo: 

>"data":[ {"_id":"xxx",**"name":"info-comun"**,"count":xxx,"__v":xxx} ] 

.

**Comment by IgnaGarcia** [comment]
solved
